# Generated by Django 4.2.2 on 2023-07-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_rename_id_orderitem__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
